### ISSUE TITLE
Install on windows + CI setup

### ISSUE THREAD

**Issue by c42f** [JuliaGeo/Proj4.jl#8]
Getting Proj4.jl to work on windows mainly involves building the C library.  This is pretty easy as a one-off, but then it'll need to be distributed from somewhere, etc, which is a bit of a pain.  OSGeo4W comes to mind.  Just grabbing it from their release area might possibly be ok, or maybe it should be done via their installer.  Latest release is here:

http://download.osgeo.org/osgeo4w/x86_64/release/proj/

**Comment by c42f** [comment]
See also some discussion on julia-geo about how to make it work with the dlls from gisinternals or GMT: https://groups.google.com/d/msg/julia-geo/vpWxaBq8VOI/4YaiX3luCAAJ

**Comment by c42f** [comment]
Looks like osgeo4w might work, though it looks like they serve the package binaries over http which is far from ideal.

Setup program: http://download.osgeo.org/osgeo4w/setup.exe

Example command line usage to install proj only:
```
osgeo4w-setup.exe --root C:\osgeo4w --quiet-mode --advanced --site  http://download.osgeo.org/osgeo4w --packages proj
```

**Comment by c42f** [comment]
Spent some more time trying to get this working on windows via osgeo4w, but it's not going well.

* Due to whatever randomness the binaries can't be installed using osgeo4w-setup.exe on windows, since `_jl_spawn()` refuses to run the executable
* Even if the setup program did run, it requires admin permissions to launch, even when displaying the command line help.  Ick.

**Comment by c42f** [comment]
See julialang/julia#15598 .  Workaround could be to go via the shell :(

Or just forget it all, and build proj ourselves...

**Comment by awbsmith** [comment]
I got Proj4 to work on Windows by:

- using the above instructions for `osgeo4w-setup.exe` to end up with `libproj.dll`; which I copied it into: 
   `C:\.julia\v0.5\Proj4\deps\usr\lib\libproj.dll`

- faking the result of the bindeps build process by creating:
    `C:\.julia\v0.5\Proj4\deps\deps.jl`
    with the contents:
```
# This is an auto-generated file; do not edit

# Pre-hooks

# Macro to load a library
macro checked_lib(libname, path)
    ((VERSION >= v"0.4.0-dev+3844" ? Base.Libdl.dlopen_e : Base.dlopen_e)(path) == C_NULL) && error("Unable to load \n\n$libname ($path)\n\nPlease re-run Pkg.build(package), and restart Julia.")
    quote const $(esc(libname)) = $path end
end

# Load dependencies
@checked_lib libproj "C:\\.julia\\v0.5\\Proj4\\deps\\usr\\lib\\libproj.dll"

# Load-hooks
```
